### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by wesslen** [alexkeeney766/Bayesian_Delta_Modeling#1]
Excellent work! Consider adding a binder (Docker) file to your repo: https://mybinder.org/

Binder file is essentially a docker file that along with adding a button on your repo README, users can click that to enable a docker container so they can run your notebooks. 

As an example, go [here](https://github.com/pymc-devs/resources) . Choose one of the Bayesian textbook/repos (eg Statistical Rethinking 2), then go to that Repo and click the Binder button where it will launch/deploy a container to run those notebooks on Binder’s cloud.

**Comment by alexkeeney766** [comment]
Always teaching me something new! Thanks Ryan.
